[package]
name = "move-linter"
version = "0.1.0"
authors = ["Aptos Labs"]
description = "The Move Linter"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptosfoundation.org/"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
codespan-reporting = { workspace = true }
move-binary-format = { workspace = true }
move-compiler = { workspace = true }
move-compiler-v2 = { workspace = true }
move-model = { workspace = true }
move-stackless-bytecode = { workspace = true }
num = { workspace = true }

[dev-dependencies]
datatest-stable = { workspace = true }
move-prover-test-utils = { workspace = true }

[features]
default = []

[[test]]
name = "testsuite"
harness = false

[lib]
doctest = false
